name: Uberjar

on: [push]

jobs:
  build:
    name: Checkout code and create uberjar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1139
          lein: 2.9.8 
      - name: Run uberjar
        run: lein uberjar
